### ISSUE TITLE
SketchFocusHelper

### ISSUE THREAD

**Issue by mischugo** [lukasondrej/sketch-focus#1]
Hello,

after installing the update to 1.05 i get a OSX pop up message

SketchFocusHelper.app can't starte because of a non verified developer .....

Best
Maik

**Comment by lukasondrej** [comment]
Thanks for reporting this @mischugo. An update to fix this is on its way very soon. In the meantime, the plugin is still fully usable, you just need to select 'Anywhere' in System Preferences -> Security and Privacy -> Allow apps downloaded from on your Mac.

**Comment by lukasondrej** [comment]
Code-signing has been fixed in 1.0.6, please update.
